Revert "Revert "Fix #7: Set base image to be radiasoft/beamsim-jupyter again""
radiasoft/container-sirepo-devbox pull request #8
Opened 2023-08-07 21:15 UTC by e-carlin

This reverts commit 1565104a67e49d307463ca6450a6525d8639401f.

I accidentally committed to main so I reverted there and I moved the commit to a PR.

Commit message of original commit (5a95760a97559c7539426ead7360cdc5feaae41a).

beamsim-jupyter provides its own ~/.post_bivio_bashrc which then sources ~/jupyter/bashrc

Also, moved common install steps for sirepo containers to installers/container-sirepo-base to share code between container-sirepo-ci and container-sirepo-devbox.

2023-08-07 21:18 UTC, e-carlin commented
Depends on https://github.com/radiasoft/download/pull/517

2023-08-07 21:29 UTC, robnagler requested changes

2023-08-07 21:29 UTC, robnagler commented on container-conf/build.sh
> +    install_repo_eval container-sirepo-base
`install_repo_eval container-sirepo-base run_user`?

2023-08-08 15:04 UTC, e-carlin commented on container-conf/build.sh
> +    install_repo_eval container-sirepo-base
5f3a975

2023-08-08 16:15 UTC, robnagler approved these changes
You merge.

2023-08-08 16:37 UTC, merged